In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("02 computer.csv")
df

        age  income student credit_rating buys_computer
0      <=30    high      no          fair            no
1      <=30    high      no     excellent            no
2   31...40    high      no          fair           yes
3       >40  medium      no          fair           yes
4       >40     low     yes          fair           yes
5       >40     low     yes     excellent            no
6   31...40     low     yes     excellent           yes
7      <=30  medium      no          fair            no
8      <=30     low     yes          fair           yes
9       >40  medium     yes          fair           yes
10     <=30  medium     yes     excellent           yes
11  31...40  medium      no     excellent           yes
12  31...40    high     yes          fair           yes
13      >40  medium      no     excellent            no

In [ ]:
df['age']= df['age'].str.replace('31...40','31-40')
df

In [ ]:
x = df.iloc[:,0:4]
y = df['buys_computer']

x

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test, y_train, y_test = train_test_split(
x,
y,
test_size=0.2,
random_state=1)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

oe_age= OrdinalEncoder(categories= [['<=30','31-40','>40']])
oe_income= OrdinalEncoder(categories= [['low','medium','high']])
oe_credit= OrdinalEncoder(categories= [['fair','excellent']])

x_train['age'] = oe_age.fit_transform(x_train[['age']])
x_train['income'] = oe_income.fit_transform(x_train[['income']])
x_train['credit_rating'] = oe_credit.fit_transform(x_train[['credit_rating']])

x_test['age'] = oe_age.fit_transform(x_test[['age']])
x_test['income'] = oe_income.fit_transform(x_test[['income']])
x_test['credit_rating'] = oe_credit.transform(x_test[['credit_rating']])

ohe = OneHotEncoder(drop = 'if_binary', sparse_output=False)

x_train[['student_yes']] = ohe.fit_transform(x_train[['student']])
x_test[['student_yes']] = ohe.transform(x_test[['student']])

x_train = x_train.drop(['student'], axis=1)
x_test = x_test.drop(['student'], axis=1)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [ ]:
x_train

In [ ]:
from sklearn.naive_bayes import CategoricalNB

In [ ]:
model = CategoricalNB()
model.fit(x_train, y_train)

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score

acc= accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc:.3%}")

Accuracy: 66.667%

In [ ]:
data = {'Actual Value':y_test,
      'Predicted Value':y_pred}
pd.DataFrame(data)

   Actual Value  Predicted Value
0             1                1
1             0                1
2             1                1